api/urls.py
from django.urls import path
from .auth_views import RegisterView, LoginView
from .post_views import PostDetailView, PostListView, CommentListView , CommentDetailView , PostLikeViewSet

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Facebook Pro API",
        default_version='v1',
        description="An api this facebook project",
        terms_of_service="#",
        contact=openapi.Contact(email="me@iamafasha.com"),
        license=openapi.License(name="Test License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)



urlpatterns = [
    path("", schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('sandbox/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('auth/register/', RegisterView.as_view(), name ="api_register"),
    path('auth/login/', LoginView.as_view(), name="api_login" ),
    path('posts/', PostListView.as_view(),name="api_post_list"),
    path('posts/<int:id>/', PostDetailView.as_view(),name="api_post_single"),
    path('posts/<int:post_id>/comments/', CommentListView.as_view(),name="api_comments_list"),
    path('posts/<int:post_id>/comments/<int:id>/', CommentDetailView.as_view(),name="api_coments_single"),
    path('posts/<int:post_id>/like/', PostLikeViewSet.as_view({'post': 'create','delete':'destroy'}) ,name="api_like"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('', include('user.urls')),
    path('<username>/',include('post.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.profile , name="profile" ),
    path('add_post/',views.create_post,name="create_post"),
    path('<int:id>/', views.single_post , name="sinlge_post" ),
    path('<int:post_id>/comments/create',views.create_comment,name="add_comment"),
    path('<int:post_id>/comment/<int:comment_id>/',views.comment,name="comment"),
    path('<int:post_id>/like', views.post_like , name="post_like" ),
]

post/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField( default=timezone.now, blank=True, null=True)
    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def __str__(self):
        return self.text[0:100]

class PostLike(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)

class PostMedia(models.Model):
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
    image = models.FileField(upload_to = './',blank=True, null=True)
    caption = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.post.text[0:40]

class Comment(models.Model):
    reply_to = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=timezone.now)

    def comment(self):
        self.save()

    def filtered_unapproved_set(self):
        pass

    def __str__(self):
        return self.text[0:50]

post/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView, CreateView
from user.forms import LoginForm
from django.utils import timezone
from .models import Post, Comment, PostLike, PostMedia
from user.models import User


# Create your views here.
def index(request):
    login_form=LoginForm()
    posts=Post.objects.filter(approved=True).order_by('-published_date')
    context = {
        "form": login_form,
        "posts":posts,
        }
    return render(request, 'post/home.html',context )

# Create your views here.
def profile(request ,username=None):
    login_form=LoginForm()
    posts=Post.objects.filter(approved=True ).order_by('-published_date')
    error = []
    try:
        user=User.objects.get(username=username)
        posts=Post.objects.filter(author=user, approved=True , ).order_by('-published_date')
    except User.DoesNotExist:
        error= {
            "message":"account never exists"
        }
        posts = {}
    context = {
        "form": login_form,
        "posts":posts,
        "error":error,
        "username":username
    }
    return render(request, 'post/timeline.html',context)

def single_post(request, username, id):
    username=User.objects.get(username=username)
    post= Post.objects.get(author = username.id, pk=id)
    context ={
        'post':post
    }
    return render(request, 'post/single_post.html',context)

def create_post(request,username):
    if(request.method=="POST"):
        text = request.POST.get('description')
        post =Post(author=request.user,text=text)
        post.save()
        images=request.FILES.getlist('upload')
        for image in images:
            post_image=PostMedia(post=post,image=image,caption="")
            post_image.save()
        return redirect('sinlge_post', username=request.user.username, id =post.id )

def comment(request, username, post_id , comment_id):
    username = User.objects.get(username=username)
    comment = Comment.objects.get(id =comment_id)
    if request.method == 'GET':
        setapprove=request.GET.get('set_approve')
        if(setapprove == "true"):
            comment.approved=True
            comment.save()
    return redirect('sinlge_post', username= username,id =post_id )

def create_comment(request,username,post_id):
    if request.method == 'POST' and request.user.is_authenticated:
        comment_text=request.POST.get('post_comment')
        try:
            Comment.objects.create(author=request.user,reply_to=Post.objects.get(id=post_id),text=comment_text,approved=False)
        except User.DoesNotExist:
            pass
        return redirect('sinlge_post', username= username,id =post_id )
    elif request.method == 'GET':
        return redirect(request.META.get('HTTP_REFERER'))

def post_like(request,username,post_id):
    if request.method == 'GET':
        action=request.GET.get('action').strip()
        post = Post.objects.get(id=post_id)
        
        if action=='like' :
            try:
                PostLike.objects.get(author=request.user,post=post)
            except PostLike.DoesNotExist:
                PostLike.objects.create(author=request.user,post=post).save()
        elif action=='unlike':
            PostLike.objects.get(author=request.user,post=post).delete()
    return redirect(request.META.get('HTTP_REFERER'))

post/templates/post/home.html
{% extends 'post/layout/default.html' %}

{% load post_likes %}
{% block posts %}
    <h2>Latest Posts</h2>

    {% if error %}
     <span>{{error.message}}</span>
    {% endif %}
    {% for post in posts %}
        <div class="card">
        <div class="card-header">
            {{ post.author.get_full_name }}
        </div>
        <div class="card-body">
            <p class="card-text">{{post.text}}</p>
        </div>
        {% if post.postmedia_set.count > 0 %}
            <img class="card-img-top" style="max-height:300px;object-fit:cover" src=" {{post.postmedia_set.all.first.image.url}}" alt="Card image cap">
        {% endif %}
        <div class="card-footer">
            <span> <a class="{% if post|is_post_liked_by:user %}liked{% endif %}" href="{% url 'post_like' post.author post.id %}?action={% if post|is_post_liked_by:user %} unlike {% else %} like {% endif %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a> {{ post.postlike_set.count }} &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;</span>
            <span> <a > <i class="fa fa-comment"></i></a> {{post.comment_set.count}}</span>
        </div>
        <div class="card-footer text-muted">
           <span>{{ post.published_date }}</span> 
            <a href="{% url 'sinlge_post' post.author.username post.id %}">view post</a>
        </div>
        </div>

        <br/>
        <br/>
    {% endfor %}
{% endblock %}

post/templates/post/single_post.html
{% extends 'post/layout/default.html' %}
{% load post_likes %}
{% load post_comments %}
{% block posts %}
<div class="card">
  <div class="card-header">
    {{post.author.first_name}} {{post.author.last_name}}
  </div>

  <div class="card-body">
    {{post.text}}
  </div>


  {% if post.postmedia_set.count > 0 %}

    {% for post_media in post.postmedia_set.all %}
    <img class="card-img-top" style="max-height:300px;object-fit:cover" src="{{post_media.image.url}}"
      alt="Card image cap">
    {% endfor %}
  {% endif %}


  <div class="card-footer">
    <span> <a class="{% if post|is_post_liked_by:user %}liked{% endif %}" href="{% url 'post_like' post.author post.id %}?action={% if post|is_post_liked_by:user %} unlike {% else %} like {% endif %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a> {{ post.postlike_set.count }} &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;</span>
    <span> <a > <i class="fa fa-comment"></i></a> {{post.comment_set.count}}</span>
  </div>

  <div class="card-footer">
    <span><a href="like" class="btn" role="button">Like</a></span>
    <span><a href="#add-comment-form" class="btn" role="button">Add Comment</a></span>
  </div>
</div>
<h5>Comments</h5>

{% for comment in post.comment_set.all|in_approved %}
<div class="card text-left">
  <div class="card-body">
    <h4 class="card-title">{{comment.author.first_name}} {{comment.author.last_name}}</h4>
    <p class="card-text">{{comment.text}}</p>
  </div>
</div>
<br>

{% endfor %}


<form action="{% url 'add_comment'  request.resolver_match.kwargs.username post.id  %}" method="post">
  {% csrf_token %} 
<div id="add-comment-form" class="form-group">
  <textarea class="form-control" name="post_comment"  rows="3"></textarea>
  <br>
  <button type="submit" class="btn btn-primary">Add Comment</button>
</div>

</form>
{% endblock posts %}


{% block aside %}
<br />
<br />
{% if request.resolver_match.kwargs.username == user.username %}
<ul class="list-group">
  <h5>Un approved comments</h5>
  {% for unapproved_comments in post.comment_set.all|in_unapproved %}
  <li class="list-group-item ">
    <h5>{{unapproved_comments.author.first_name}} {{unapproved_comments.author.last_name}}</h5>
    <span>{{unapproved_comments.text }}</span>
    <br>
    <br>
    <a href="{% url 'comment' request.resolver_match.kwargs.username post.id unapproved_comments.id %}?set_approve=true" class="btn btn-primary">Approve</a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% endblock aside %}

post/templates/post/timeline.html
{% extends 'post/layout/default.html' %}
{% load post_likes %}

{% block posts %}
    <h2>Latest Posts</h2>

    {% if error %}
     <span>{{error.message}}</span>
    {% endif %}
    {% for post in posts %}
        <div class="card">
        <div class="card-header">
            {{ post.author.get_full_name }}
        </div>
        <div class="card-body">
            <p class="card-text">{{post}}</p>
        </div>



        {% if post.postmedia_set.count > 0 %}
            <img class="card-img-top" style="max-height:300px;object-fit:cover" src=" {{post.postmedia_set.all.first.image.url}}" alt="Card image cap">
        {% endif %}

        <div class="card-footer">
            <span> <a class="{% if post|is_post_liked_by:user %}liked{% endif %}" href="{% url 'post_like' post.author post.id %}?action={% if post|is_post_liked_by:user %} unlike {% else %} like {% endif %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a> {{ post.postlike_set.count }} &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;</span>
            <span> <a > <i class="fa fa-comment"></i></a> {{post.comment_set.count}}</span>
        </div>
        <div class="card-footer text-muted">
           <span>{{ post.published_date }}</span> 
           <a href="{% url 'sinlge_post' post.author.username post.id %}">view post</a>
        </div>
        </div>

        <br/>
        <br/>
    {% endfor %}
{% endblock %}

    {% block aside %}

    <br>
    <br>
    <br>
        <form action="" method="post">

            <!-- Default unchecked -->
            <div class="custom-control custom-radio">
                <input type="radio" class="custom-control-input" id="defaultUnchecked" name="defaultExampleRadios">
                <label class="custom-control-label" for="defaultUnchecked">All</label>
            </div>


            <!-- Default unchecked -->
            <div class="custom-control custom-radio">
                <input type="radio" class="custom-control-input" id="defaultUnchecked" name="defaultExampleRadios">
                <label class="custom-control-label" for="defaultUnchecked">Published & Approved</label>
            </div>
            
            <!-- Default checked -->
            <div class="custom-control custom-radio">
                <input type="radio" class="custom-control-input" id="defaultChecked" name="defaultExampleRadios" checked>
                <label class="custom-control-label" for="defaultChecked">Un Approved</label>
            </div>
        </form>
    {% endblock aside %}

